FROM openjdk:17
LABEL author="decagon"
WORKDIR /app
EXPOSE 8080
COPY ScoreCard-016-0.0.1-SNAPSHOT.jar /app/ScoreCard-016-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/app/ScoreCard-016-0.0.1-SNAPSHOT.jar"]